version: '3.8'

services: 
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes: 
      - ./frontend:/app
      - /app/node_modules
    networks:
      - immo-network
    

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
      # ADd other environment variables
    volumes:
      - ./backend:/app
    networks:
      - immo-network

networks:
  immo-network:
    driver: bridge