version: '3.8'

services: 
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes: 
      - ./frontend:/app
      - /app/node_modules
    networks:
      - immo-network
    command: npm run dev -- --host 0.0.0.0 --port 3001
    

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/immo
      # Set the API key directly instead of using the environment variable
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./backend:/app
    networks:
      - immo-network
    depends_on:
      - postgres
    command: >
      bash -c "pip install tenacity openai &&
      echo 'Waiting for PostgreSQL to start...' &&
      sleep 5 &&
      echo 'Running database migrations...' &&
      alembic upgrade head || (alembic revision --autogenerate -m 'Initial migration' && alembic upgrade head) &&
      echo 'Starting application...' &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000"

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=immo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - immo-network
      
networks:
  immo-network:
    driver: bridge

volumes:
  postgres_data:
