version: '3.8'

services: 
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes: 
      - ./frontend:/app
      - /app/node_modules
    networks:
      - immo-network
    

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/immo
      # Add other environment variables
    volumes:
      - ./backend:/app
    networks:
      - immo-network
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=immo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - immo-network
      
networks:
  immo-network:
    driver: bridge

volumes:
  postgres_data:
