# app/models/enums.py
from enum import Enum

class GenerationStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSING_OUTLINE = "PROCESSING_OUTLINE"
    OUTLINE_COMPLETED = "OUTLINE_COMPLETED"
    PROCESSING_SECTIONS = "PROCESSING_SECTIONS"
    SECTIONS_COMPLETED = "SECTIONS_COMPLETED"
    PROCESSING_SCENES = "PROCESSING_SCENES"
    SCENES_COMPLETED = "SCENES_COMPLETED"
    PROCESSING_PROSE = "PROCESSING_PROSE"
    COMPLETED = "COMPLETED"
    PARTIALLY_COMPLETED = "PARTIALLY_COMPLETED"
    FAILED = "FAILED"

class SectionStatus(str, Enum):
    PENDING = "PENDING"
    READY_FOR_SCENES = "READY_FOR_SCENES"
    GENERATING_SCENES = "GENERATING_SCENES"
    SCENES_COMPLETED = "SCENES_COMPLETED"
    PROCESSING_SCENES = "PROCESSING_SCENES"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class SceneStatus(str, Enum):
    PENDING = "PENDING"
    READY_FOR_PROSE = "READY_FOR_PROSE"
    GENERATING = "GENERATING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
